version: "3.7"

services:
  postgres:
    image: postgres:15
    container_name: postgres1
    command: postgres 
      -c 'max_connections=300'
      -c 'shared_buffers=256MB'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
